{% set name = "dpkt" %}
{% set version = "1.9.4" %}
{% set sha256 = "f4e579cbaf6e2285ebf3a9e84019459b4367636bac079ba169527e582fca48b4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - dpkt

about:
  home: http://github.com/kbandla/dpkt
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: fast, simple packet creation / parsing, with definitions for the basic TCP/IP protocols
  description: |
    dpkt is a simple packet creation / parsing, with definitions for the basic TCP/IP protocols
    and is implemented in pure python
  doc_url: https://dpkt.readthedocs.io
  dev_url: http://github.com/kbandla/dpkt
